### ISSUE TITLE
Rating icons display vertically

### ISSUE THREAD

**Issue by maxratajczak** [awran5/react-simple-star-rating#29]
When I display the rating, the icons are stacked vertically, I tried setting it in a flexbox but it didn't help.

<img width="493" alt="Screen Shot 2022-10-19 at 3 30 49 PM" src="https://user-images.githubusercontent.com/75450072/196786187-121be28c-afff-49c9-b957-a124538a5175.png">

<img width="373" alt="Screen Shot 2022-10-19 at 3 31 03 PM" src="https://user-images.githubusercontent.com/75450072/196786218-69063fbf-913a-42a1-a4ec-5ec1ad67233c.png">

**Comment by awran5** [comment]
Hi @maxratajczak 

Try to add the `flex` className to `emptyClassName` prop: 


```ts

<Rating 
...
emptyClassName="flex"
...
 />
```
Or add some CSS to your stylesheet: 
```css
.react-simple-star-rating .filled-icons {
  display: inline-block !important;
}

.react-simple-star-rating .empty-icons {
  display: flex !important;
}
```
